# defaults
user = {
    "minify": False,
    "outputFile": "dist/out.html",
}

EXTENSION = "mark"
MODULE_DECLERATION = "// mod"
PACKAGE_COMMENT = "Generated by Mark. <https://github.com/baris-inandi/mark>"  # noqa
CONFIG_DOCS = "https://example.com/docs/mark.config.json"
ERROR_NO_EXIT = False
