# defaults
user = {"minify": False, "outputFile": "dist/out.html", "indent": 2}

EXTENSION = "mark"
MODULE_DECLERATION = "// mod"
PACKAGE_COMMENT = "Generated by mark-python. <https://github.com/baris-inandi/mark>"  # noqa
CONFIG_DOCS = "https://example.com/docs/markrc.json"
ERROR_NO_EXIT = False
